#spring:
#  datasources:
#    -
#      name: db1
#      url: jdbc:mysql://localhost:3306/db1
#      username: admin
#      password: admin
#      driver-class-name: com.mysql.jdbc.Driver
#    -
#      name: db2
#      url: jdbc:mysql://localhost:3306/db2
#      username: admin
#      password: admin
#      driver-class-name: com.mysql.jdbc.Driver